### ISSUE TITLE
Corriger la superposition du texte avec le bouton de suppression des messages

### ISSUE THREAD

**Issue by hardware** [mondediefr/mondedie-chat#1]
Lorsque le texte du message est long, il se superpose avec le bouton de suppression.

**Comment by al3xLvs** [comment]
Le bug est tjrs là, j'ai trouvé la solution.
Au lieu de mettre le lien en `display: absolute;` il faut utiliser `float: right;`

Solution:
fichier _section-center.scss

``` scss
.option {
  float: right;
  font-size: rem(14px);
  color: #aaa;
  cursor: pointer;
  &:hover {
    color: #3498db;
  }
}
```

Par contre un autre problème se pose, j'ai la scrollbar sur macosx qui me génère un bug.
Elle empêche parfois de cliquer sur la croix.
Pour ça il faudrait custom la scrollbar ce qui force l'affichage permanent de la barre, ce qui résout le problème

```
::-webkit-scrollbar {
}
```

par contre très mal supporté par les navigateurs. Faudrait trouver une solution par trop lourde au niveau du code.
